RuntimeError: dictionary changed size during iteration
This issue happen few or more times in a hour.  Now after that change program has been running without issue many hours.  This is very hard to reproduce as it come as a side effect of sort of big program running.

List of items is essentially copy so therefore cannot change during the iteration.

Here is error message:

RuntimeError: dictionary changed size during iteration
binding propagation for 17 active links took 0.011 s
dictionary changed size during iteration
Traceback (most recent call last):
  File "/home/hsyrja/.local/lib/python3.10/site-packages/nicegui/outbox.py", line 49, in loop
    data = {
  File "/home/hsyrja/.local/lib/python3.10/site-packages/nicegui/outbox.py", line 49, in <dictcomp>
    data = {
RuntimeError: dictionary changed size during iteration